export const TEST_TAKE = 'TEST_TAKE';
export const TEST_TAKE_EVERY = 'TEST_TAKE_EVERY';
export const TEST_TAKE_EVERY_MANUAL = 'TEST_TAKE_EVERY_MANUAL';
export const TEST_TAKE_LATEST = 'TEST_TAKE_LATEST';
export const TEST_TAKE_LEADING = 'TEST_TAKE_LEADING';
